name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      
      - name: Install dependencies
        run: yarn
      
      - name: Run build
        run: yarn build
      
      - name: Run deploy
        run: CF_API_TOKEN={{ secrets.CFW_TOKEN }} yarn deploy
